export const DEFAULT_PHONE_COUNTRY_CODE = 'GB';
export const DEFAULT_BANK_ACCOUNT_CURRENCY = 'GBP';

export const IBAN_COUNTRY_CODES = [
  'AL',
  'AD',
  'AT',
  'AZ',
  'BH',
  'BY',
  'BE',
  'BA',
  'BG',
  'CR',
  'HR',
  'CY',
  'CZ',
  'DK',
  'DO',
  'EE',
  'FO',
  'FI',
  'FR',
  'GE',
  'DE',
  'GI',
  'GR',
  'GL',
  'VA',
  'HU',
  'IS',
  'IQ',
  'IE',
  'IL',
  'IT',
  'JO',
  'KZ',
  'KW',
  'LV',
  'LB',
  'LI',
  'LT',
  'LU',
  'MT',
  'MR',
  'MU',
  'MD',
  'MC',
  'ME',
  'NL',
  'MK',
  'NO',
  'PS',
  'PL',
  'PT',
  'QA',
  'RO',
  'SM',
  'SA',
  'RS',
  'SC',
  'SK',
  'SI',
  'ES',
  'SE',
  'CH',
  'TN',
  'TR',
  'UA',
  'AE',
  'GF',
  'GP',
  'MQ',
  'RE',
  'PF',
  'TF',
  'YT',
  'NC',
  'BL',
  'MF',
  'PM',
  'WF',
];

export const COUNTRY_LIST: Array<{
  countryCode: string;
  countryName: string;
  currencyCode?: string;
  currencyName?: string;
}> = [
  { countryCode: 'AF', countryName: 'Afghanistan', currencyCode: 'AFN', currencyName: 'Afghani' },
  { countryCode: 'AX', countryName: 'Aland Islands', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'AL', countryName: 'Albania', currencyCode: 'ALL', currencyName: 'Lek' },
  { countryCode: 'DZ', countryName: 'Algeria', currencyCode: 'DZD', currencyName: 'Algerian Dinar' },
  { countryCode: 'AS', countryName: 'American Samoa', currencyCode: 'USD', currencyName: 'US Dollar' },
  { countryCode: 'AD', countryName: 'Andorra', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'AO', countryName: 'Angola', currencyCode: 'AOA', currencyName: 'Kwanza' },
  { countryCode: 'AI', countryName: 'Anguilla', currencyCode: 'XCD', currencyName: 'East Caribbean Dollar' },
  { countryCode: 'AQ', countryName: 'Antarctica' },
  { countryCode: 'AG', countryName: 'Antigua and Barbuda', currencyCode: 'XCD', currencyName: 'East Caribbean Dollar' },
  { countryCode: 'AR', countryName: 'Argentina', currencyCode: 'ARS', currencyName: 'Argentine Peso' },
  { countryCode: 'AM', countryName: 'Armenia', currencyCode: 'AMD', currencyName: 'Armenian Dram' },
  { countryCode: 'AW', countryName: 'Aruba', currencyCode: 'AWG', currencyName: 'Aruban Florin' },
  { countryCode: 'AU', countryName: 'Australia', currencyCode: 'AUD', currencyName: 'Australian Dollar' },
  { countryCode: 'AT', countryName: 'Austria', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'AZ', countryName: 'Azerbaijan', currencyCode: 'AZN', currencyName: 'Azerbaijan Manat' },
  { countryCode: 'BS', countryName: 'Bahamas', currencyCode: 'BSD', currencyName: 'Bahamian Dollar' },
  { countryCode: 'BH', countryName: 'Bahrain', currencyCode: 'BHD', currencyName: 'Bahraini Dinar' },
  { countryCode: 'BD', countryName: 'Bangladesh', currencyCode: 'BDT', currencyName: 'Taka' },
  { countryCode: 'BB', countryName: 'Barbados', currencyCode: 'BBD', currencyName: 'Barbados Dollar' },
  { countryCode: 'BY', countryName: 'Belarus', currencyCode: 'BYN', currencyName: 'Belarusian Ruble' },
  { countryCode: 'BE', countryName: 'Belgium', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'BZ', countryName: 'Belize', currencyCode: 'BZD', currencyName: 'Belize Dollar' },
  { countryCode: 'BJ', countryName: 'Benin', currencyCode: 'XOF', currencyName: 'CFA Franc BCEAO' },
  { countryCode: 'BM', countryName: 'Bermuda', currencyCode: 'BMD', currencyName: 'Bermudian Dollar' },
  { countryCode: 'BT', countryName: 'Bhutan', currencyCode: 'BTN', currencyName: 'Ngultrum' },
  { countryCode: 'BO', countryName: 'Bolivia', currencyCode: 'BOB', currencyName: 'Boliviano' },
  {
    countryCode: 'BQ',
    countryName: 'Bonaire, Sint Eustatius and Saba',
    currencyCode: 'USD',
    currencyName: 'US Dollar',
  },
  { countryCode: 'BA', countryName: 'Bosnia and Herzegovina', currencyCode: 'BAM', currencyName: 'Convertible Mark' },
  { countryCode: 'BW', countryName: 'Botswana', currencyCode: 'BWP', currencyName: 'Pula' },
  { countryCode: 'BV', countryName: 'Bouvet Island', currencyCode: 'NOK', currencyName: 'Norwegian Krone' },
  { countryCode: 'BR', countryName: 'Brazil', currencyCode: 'BRL', currencyName: 'Brazilian Real' },
  { countryCode: 'IO', countryName: 'British Indian Ocean Territory', currencyCode: 'USD', currencyName: 'US Dollar' },
  { countryCode: 'BN', countryName: 'Brunei Darussalam', currencyCode: 'BND', currencyName: 'Brunei Dollar' },
  { countryCode: 'BG', countryName: 'Bulgaria', currencyCode: 'BGN', currencyName: 'Bulgarian Lev' },
  { countryCode: 'BF', countryName: 'Burkina Faso', currencyCode: 'XOF', currencyName: 'CFA Franc BCEAO' },
  { countryCode: 'BI', countryName: 'Burundi', currencyCode: 'BIF', currencyName: 'Burundi Franc' },
  { countryCode: 'CV', countryName: 'Cabo Verde', currencyCode: 'CVE', currencyName: 'Cabo Verde Escudo' },
  { countryCode: 'KH', countryName: 'Cambodia', currencyCode: 'KHR', currencyName: 'Riel' },
  { countryCode: 'CM', countryName: 'Cameroon', currencyCode: 'XAF', currencyName: 'CFA Franc BEAC' },
  { countryCode: 'CA', countryName: 'Canada', currencyCode: 'CAD', currencyName: 'Canadian Dollar' },
  { countryCode: 'KY', countryName: 'Cayman Islands', currencyCode: 'KYD', currencyName: 'Cayman Islands Dollar' },
  { countryCode: 'CF', countryName: 'Central African Republic', currencyCode: 'XAF', currencyName: 'CFA Franc BEAC' },
  { countryCode: 'TD', countryName: 'Chad', currencyCode: 'XAF', currencyName: 'CFA Franc BEAC' },
  { countryCode: 'CL', countryName: 'Chile', currencyCode: 'CLP', currencyName: 'Chilean Peso' },
  { countryCode: 'CN', countryName: 'China', currencyCode: 'CNY', currencyName: 'Yuan Renminbi' },
  { countryCode: 'CX', countryName: 'Christmas Island', currencyCode: 'AUD', currencyName: 'Australian Dollar' },
  { countryCode: 'CC', countryName: 'Cocos (Keeling) Islands', currencyCode: 'AUD', currencyName: 'Australian Dollar' },
  { countryCode: 'CO', countryName: 'Colombia', currencyCode: 'COP', currencyName: 'Colombian Peso' },
  { countryCode: 'KM', countryName: 'Comoros', currencyCode: 'KMF', currencyName: 'Comorian Franc\u00a0' },
  {
    countryCode: 'CD',
    countryName: 'Congo, the Democratic Republic of the',
    currencyCode: 'CDF',
    currencyName: 'Congolese Franc',
  },
  { countryCode: 'CG', countryName: 'Congo', currencyCode: 'XAF', currencyName: 'CFA Franc BEAC' },
  { countryCode: 'CK', countryName: 'Cook Islands', currencyCode: 'NZD', currencyName: 'New Zealand Dollar' },
  { countryCode: 'CR', countryName: 'Costa Rica', currencyCode: 'CRC', currencyName: 'Costa Rican Colon' },
  { countryCode: 'CI', countryName: "Cote d'Ivoire", currencyCode: 'XOF', currencyName: 'CFA Franc BCEAO' },
  { countryCode: 'HR', countryName: 'Croatia', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'CU', countryName: 'Cuba', currencyCode: 'CUP', currencyName: 'Cuban Peso' },
  { countryCode: 'CW', countryName: 'Curacao', currencyCode: 'ANG', currencyName: 'Netherlands Antillean Guilder' },
  { countryCode: 'CY', countryName: 'Cyprus', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'CZ', countryName: 'Czech Republic', currencyCode: 'CZK', currencyName: 'Czech Koruna' },
  { countryCode: 'DK', countryName: 'Denmark', currencyCode: 'DKK', currencyName: 'Danish Krone' },
  { countryCode: 'DJ', countryName: 'Djibouti', currencyCode: 'DJF', currencyName: 'Djibouti Franc' },
  { countryCode: 'DM', countryName: 'Dominica', currencyCode: 'XCD', currencyName: 'East Caribbean Dollar' },
  { countryCode: 'DO', countryName: 'Dominican Republic', currencyCode: 'DOP', currencyName: 'Dominican Peso' },
  { countryCode: 'EC', countryName: 'Ecuador', currencyCode: 'USD', currencyName: 'US Dollar' },
  { countryCode: 'EG', countryName: 'Egypt', currencyCode: 'EGP', currencyName: 'Egyptian Pound' },
  { countryCode: 'SV', countryName: 'El Salvador', currencyCode: 'SVC', currencyName: 'El Salvador Colon' },
  { countryCode: 'GQ', countryName: 'Equatorial Guinea', currencyCode: 'XAF', currencyName: 'CFA Franc BEAC' },
  { countryCode: 'ER', countryName: 'Eritrea', currencyCode: 'ERN', currencyName: 'Nakfa' },
  { countryCode: 'EE', countryName: 'Estonia', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'SZ', countryName: 'Eswatini', currencyCode: 'SZL', currencyName: 'Lilangeni' },
  { countryCode: 'ET', countryName: 'Ethiopia', currencyCode: 'ETB', currencyName: 'Ethiopian Birr' },
  {
    countryCode: 'FK',
    countryName: 'Falkland Islands (Malvinas)',
    currencyCode: 'FKP',
    currencyName: 'Falkland Islands Pound',
  },
  { countryCode: 'FO', countryName: 'Faroe Islands', currencyCode: 'DKK', currencyName: 'Danish Krone' },
  { countryCode: 'FJ', countryName: 'Fiji', currencyCode: 'FJD', currencyName: 'Fiji Dollar' },
  { countryCode: 'FI', countryName: 'Finland', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'FR', countryName: 'France', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'GF', countryName: 'French Guiana', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'PF', countryName: 'French Polynesia', currencyCode: 'XPF', currencyName: 'CFP Franc' },
  { countryCode: 'TF', countryName: 'French Southern Territories', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'GA', countryName: 'Gabon', currencyCode: 'XAF', currencyName: 'CFA Franc BEAC' },
  { countryCode: 'GM', countryName: 'Gambia', currencyCode: 'GMD', currencyName: 'Dalasi' },
  { countryCode: 'GE', countryName: 'Georgia', currencyCode: 'GEL', currencyName: 'Lari' },
  { countryCode: 'DE', countryName: 'Germany', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'GH', countryName: 'Ghana', currencyCode: 'GHS', currencyName: 'Ghana Cedi' },
  { countryCode: 'GI', countryName: 'Gibraltar', currencyCode: 'GIP', currencyName: 'Gibraltar Pound' },
  { countryCode: 'GR', countryName: 'Greece', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'GL', countryName: 'Greenland', currencyCode: 'DKK', currencyName: 'Danish Krone' },
  { countryCode: 'GD', countryName: 'Grenada', currencyCode: 'XCD', currencyName: 'East Caribbean Dollar' },
  { countryCode: 'GP', countryName: 'Guadeloupe', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'GU', countryName: 'Guam', currencyCode: 'USD', currencyName: 'US Dollar' },
  { countryCode: 'GT', countryName: 'Guatemala', currencyCode: 'GTQ', currencyName: 'Quetzal' },
  { countryCode: 'GG', countryName: 'Guernsey', currencyCode: 'GBP', currencyName: 'Pound Sterling' },
  { countryCode: 'GN', countryName: 'Guinea', currencyCode: 'GNF', currencyName: 'Guinean Franc' },
  { countryCode: 'GW', countryName: 'Guinea-Bissau', currencyCode: 'XOF', currencyName: 'CFA Franc BCEAO' },
  { countryCode: 'GY', countryName: 'Guyana', currencyCode: 'GYD', currencyName: 'Guyana Dollar' },
  { countryCode: 'HT', countryName: 'Haiti', currencyCode: 'HTG', currencyName: 'Gourde' },
  {
    countryCode: 'HM',
    countryName: 'Heard Island and McDonald Islands',
    currencyCode: 'AUD',
    currencyName: 'Australian Dollar',
  },
  { countryCode: 'VA', countryName: 'Holy See (Vatican City State)', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'HN', countryName: 'Honduras', currencyCode: 'HNL', currencyName: 'Lempira' },
  { countryCode: 'HK', countryName: 'Hong Kong', currencyCode: 'HKD', currencyName: 'Hong Kong Dollar' },
  { countryCode: 'HU', countryName: 'Hungary', currencyCode: 'HUF', currencyName: 'Forint' },
  { countryCode: 'IS', countryName: 'Iceland', currencyCode: 'ISK', currencyName: 'Iceland Krona' },
  { countryCode: 'IN', countryName: 'India', currencyCode: 'INR', currencyName: 'Indian Rupee' },
  { countryCode: 'ID', countryName: 'Indonesia', currencyCode: 'IDR', currencyName: 'Rupiah' },
  { countryCode: 'IR', countryName: 'Iran, Islamic Republic of', currencyCode: 'IRR', currencyName: 'Iranian Rial' },
  { countryCode: 'IQ', countryName: 'Iraq', currencyCode: 'IQD', currencyName: 'Iraqi Dinar' },
  { countryCode: 'IE', countryName: 'Ireland', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'IM', countryName: 'Isle of Man', currencyCode: 'GBP', currencyName: 'Pound Sterling' },
  { countryCode: 'IL', countryName: 'Israel', currencyCode: 'ILS', currencyName: 'New Israeli Sheqel' },
  { countryCode: 'IT', countryName: 'Italy', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'JM', countryName: 'Jamaica', currencyCode: 'JMD', currencyName: 'Jamaican Dollar' },
  { countryCode: 'JP', countryName: 'Japan', currencyCode: 'JPY', currencyName: 'Yen' },
  { countryCode: 'JE', countryName: 'Jersey', currencyCode: 'GBP', currencyName: 'Pound Sterling' },
  { countryCode: 'JO', countryName: 'Jordan', currencyCode: 'JOD', currencyName: 'Jordanian Dinar' },
  { countryCode: 'KZ', countryName: 'Kazakhstan', currencyCode: 'KZT', currencyName: 'Tenge' },
  { countryCode: 'KE', countryName: 'Kenya', currencyCode: 'KES', currencyName: 'Kenyan Shilling' },
  { countryCode: 'KI', countryName: 'Kiribati', currencyCode: 'AUD', currencyName: 'Australian Dollar' },
  {
    countryCode: 'KP',
    countryName: "Korea, Democratic People's Republic of",
    currencyCode: 'KPW',
    currencyName: 'North Korean Won',
  },
  { countryCode: 'KR', countryName: 'Korea, Republic of', currencyCode: 'KRW', currencyName: 'Won' },
  { countryCode: 'KW', countryName: 'Kuwait', currencyCode: 'KWD', currencyName: 'Kuwaiti Dinar' },
  { countryCode: 'KG', countryName: 'Kyrgyzstan', currencyCode: 'KGS', currencyName: 'Som' },
  { countryCode: 'LA', countryName: "Lao People's Democratic Republic", currencyCode: 'LAK', currencyName: 'Lao Kip' },
  { countryCode: 'LV', countryName: 'Latvia', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'LB', countryName: 'Lebanon', currencyCode: 'LBP', currencyName: 'Lebanese Pound' },
  { countryCode: 'LS', countryName: 'Lesotho', currencyCode: 'LSL', currencyName: 'Loti' },
  { countryCode: 'LR', countryName: 'Liberia', currencyCode: 'LRD', currencyName: 'Liberian Dollar' },
  { countryCode: 'LY', countryName: 'Libyan Arab Jamahiriya', currencyCode: 'LYD', currencyName: 'Libyan Dinar' },
  { countryCode: 'LI', countryName: 'Liechtenstein', currencyCode: 'CHF', currencyName: 'Swiss Franc' },
  { countryCode: 'LT', countryName: 'Lithuania', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'LU', countryName: 'Luxembourg', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'MO', countryName: 'Macao', currencyCode: 'MOP', currencyName: 'Pataca' },
  { countryCode: 'MG', countryName: 'Madagascar', currencyCode: 'MGA', currencyName: 'Malagasy Ariary' },
  { countryCode: 'MW', countryName: 'Malawi', currencyCode: 'MWK', currencyName: 'Malawi Kwacha' },
  { countryCode: 'MY', countryName: 'Malaysia', currencyCode: 'MYR', currencyName: 'Malaysian Ringgit' },
  { countryCode: 'MV', countryName: 'Maldives', currencyCode: 'MVR', currencyName: 'Rufiyaa' },
  { countryCode: 'ML', countryName: 'Mali', currencyCode: 'XOF', currencyName: 'CFA Franc BCEAO' },
  { countryCode: 'MT', countryName: 'Malta', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'MH', countryName: 'Marshall Islands', currencyCode: 'USD', currencyName: 'US Dollar' },
  { countryCode: 'MQ', countryName: 'Martinique', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'MR', countryName: 'Mauritania', currencyCode: 'MRU', currencyName: 'Ouguiya' },
  { countryCode: 'MU', countryName: 'Mauritius', currencyCode: 'MUR', currencyName: 'Mauritius Rupee' },
  { countryCode: 'YT', countryName: 'Mayotte', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'MX', countryName: 'Mexico', currencyCode: 'MXN', currencyName: 'Mexican Peso' },
  { countryCode: 'FM', countryName: 'Micronesia, Federated States of', currencyCode: 'USD', currencyName: 'US Dollar' },
  { countryCode: 'MD', countryName: 'Moldova, Republic of', currencyCode: 'MDL', currencyName: 'Moldovan Leu' },
  { countryCode: 'MC', countryName: 'Monaco', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'MN', countryName: 'Mongolia', currencyCode: 'MNT', currencyName: 'Tugrik' },
  { countryCode: 'ME', countryName: 'Montenegro', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'MS', countryName: 'Montserrat', currencyCode: 'XCD', currencyName: 'East Caribbean Dollar' },
  { countryCode: 'MA', countryName: 'Morocco', currencyCode: 'MAD', currencyName: 'Moroccan Dirham' },
  { countryCode: 'MZ', countryName: 'Mozambique', currencyCode: 'MZN', currencyName: 'Mozambique Metical' },
  { countryCode: 'MM', countryName: 'Myanmar', currencyCode: 'MMK', currencyName: 'Kyat' },
  { countryCode: 'NA', countryName: 'Namibia', currencyCode: 'NAD', currencyName: 'Namibia Dollar' },
  { countryCode: 'NR', countryName: 'Nauru', currencyCode: 'AUD', currencyName: 'Australian Dollar' },
  { countryCode: 'NP', countryName: 'Nepal', currencyCode: 'NPR', currencyName: 'Nepalese Rupee' },
  { countryCode: 'NL', countryName: 'Netherlands', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'NC', countryName: 'New Caledonia', currencyCode: 'XPF', currencyName: 'CFP Franc' },
  { countryCode: 'NZ', countryName: 'New Zealand', currencyCode: 'NZD', currencyName: 'New Zealand Dollar' },
  { countryCode: 'NI', countryName: 'Nicaragua', currencyCode: 'NIO', currencyName: 'Cordoba Oro' },
  { countryCode: 'NE', countryName: 'Niger', currencyCode: 'XOF', currencyName: 'CFA Franc BCEAO' },
  { countryCode: 'NG', countryName: 'Nigeria', currencyCode: 'NGN', currencyName: 'Naira' },
  { countryCode: 'NU', countryName: 'Niue', currencyCode: 'NZD', currencyName: 'New Zealand Dollar' },
  { countryCode: 'NF', countryName: 'Norfolk Island', currencyCode: 'AUD', currencyName: 'Australian Dollar' },
  { countryCode: 'MK', countryName: 'North Macedonia', currencyCode: 'MKD', currencyName: 'Denar' },
  { countryCode: 'MP', countryName: 'Northern Mariana Islands', currencyCode: 'USD', currencyName: 'US Dollar' },
  { countryCode: 'NO', countryName: 'Norway', currencyCode: 'NOK', currencyName: 'Norwegian Krone' },
  { countryCode: 'OM', countryName: 'Oman', currencyCode: 'OMR', currencyName: 'Rial Omani' },
  { countryCode: 'PK', countryName: 'Pakistan', currencyCode: 'PKR', currencyName: 'Pakistan Rupee' },
  { countryCode: 'PW', countryName: 'Palau', currencyCode: 'USD', currencyName: 'US Dollar' },
  { countryCode: 'PS', countryName: 'Palestine, State of', currencyCode: 'ILS', currencyName: 'New Israeli Sheqel' },
  { countryCode: 'PA', countryName: 'Panama', currencyCode: 'PAB', currencyName: 'Balboa' },
  { countryCode: 'PG', countryName: 'Papua New Guinea', currencyCode: 'PGK', currencyName: 'Kina' },
  { countryCode: 'PY', countryName: 'Paraguay', currencyCode: 'PYG', currencyName: 'Guarani' },
  { countryCode: 'PE', countryName: 'Peru', currencyCode: 'PEN', currencyName: 'Sol' },
  { countryCode: 'PH', countryName: 'Philippines', currencyCode: 'PHP', currencyName: 'Philippine Peso' },
  { countryCode: 'PN', countryName: 'Pitcairn', currencyCode: 'NZD', currencyName: 'New Zealand Dollar' },
  { countryCode: 'PL', countryName: 'Poland', currencyCode: 'PLN', currencyName: 'Zloty' },
  { countryCode: 'PT', countryName: 'Portugal', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'PR', countryName: 'Puerto Rico', currencyCode: 'USD', currencyName: 'US Dollar' },
  { countryCode: 'QA', countryName: 'Qatar', currencyCode: 'QAR', currencyName: 'Qatari Rial' },
  { countryCode: 'RE', countryName: 'Reunion', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'RO', countryName: 'Romania', currencyCode: 'RON', currencyName: 'Romanian Leu' },
  { countryCode: 'RU', countryName: 'Russian Federation', currencyCode: 'RUB', currencyName: 'Russian Ruble' },
  { countryCode: 'RW', countryName: 'Rwanda', currencyCode: 'RWF', currencyName: 'Rwanda Franc' },
  { countryCode: 'BL', countryName: 'Saint Barthelemy', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'SH', countryName: 'Saint Helena', currencyCode: 'SHP', currencyName: 'Saint Helena Pound' },
  {
    countryCode: 'KN',
    countryName: 'Saint Kitts and Nevis',
    currencyCode: 'XCD',
    currencyName: 'East Caribbean Dollar',
  },
  { countryCode: 'LC', countryName: 'Saint Lucia', currencyCode: 'XCD', currencyName: 'East Caribbean Dollar' },
  { countryCode: 'MF', countryName: 'Saint Martin (French part)', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'PM', countryName: 'Saint Pierre and Miquelon', currencyCode: 'EUR', currencyName: 'Euro' },
  {
    countryCode: 'VC',
    countryName: 'Saint Vincent and the Grenadines',
    currencyCode: 'XCD',
    currencyName: 'East Caribbean Dollar',
  },
  { countryCode: 'WS', countryName: 'Samoa', currencyCode: 'WST', currencyName: 'Tala' },
  { countryCode: 'SM', countryName: 'San Marino', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'ST', countryName: 'Sao Tome and Principe', currencyCode: 'STN', currencyName: 'Dobra' },
  { countryCode: 'SA', countryName: 'Saudi Arabia', currencyCode: 'SAR', currencyName: 'Saudi Riyal' },
  { countryCode: 'SN', countryName: 'Senegal', currencyCode: 'XOF', currencyName: 'CFA Franc BCEAO' },
  { countryCode: 'RS', countryName: 'Serbia', currencyCode: 'RSD', currencyName: 'Serbian Dinar' },
  { countryCode: 'SC', countryName: 'Seychelles', currencyCode: 'SCR', currencyName: 'Seychelles Rupee' },
  { countryCode: 'SL', countryName: 'Sierra Leone', currencyCode: 'SLE', currencyName: 'Leone' },
  { countryCode: 'SG', countryName: 'Singapore', currencyCode: 'SGD', currencyName: 'Singapore Dollar' },
  {
    countryCode: 'SX',
    countryName: 'Sint Maarten (Dutch part)',
    currencyCode: 'ANG',
    currencyName: 'Netherlands Antillean Guilder',
  },
  { countryCode: 'SK', countryName: 'Slovakia', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'SI', countryName: 'Slovenia', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'SB', countryName: 'Solomon Islands', currencyCode: 'SBD', currencyName: 'Solomon Islands Dollar' },
  { countryCode: 'SO', countryName: 'Somalia', currencyCode: 'SOS', currencyName: 'Somali Shilling' },
  { countryCode: 'ZA', countryName: 'South Africa', currencyCode: 'ZAR', currencyName: 'Rand' },
  {
    countryCode: 'GS',
    countryName: 'South Georgia and the South Sandwich Islands',
    currencyCode: 'GBP',
    currencyName: 'Pound Sterling',
  },
  { countryCode: 'SS', countryName: 'South Sudan', currencyCode: 'SSP', currencyName: 'South Sudanese Pound' },
  { countryCode: 'ES', countryName: 'Spain', currencyCode: 'EUR', currencyName: 'Euro' },
  { countryCode: 'LK', countryName: 'Sri Lanka', currencyCode: 'LKR', currencyName: 'Sri Lanka Rupee' },
  { countryCode: 'SD', countryName: 'Sudan', currencyCode: 'SDG', currencyName: 'Sudanese Pound' },
  { countryCode: 'SR', countryName: 'Suriname', currencyCode: 'SRD', currencyName: 'Surinam Dollar' },
  { countryCode: 'SJ', countryName: 'Svalbard and Jan Mayen', currencyCode: 'NOK', currencyName: 'Norwegian Krone' },
  { countryCode: 'SE', countryName: 'Sweden', currencyCode: 'SEK', currencyName: 'Swedish Krona' },
  { countryCode: 'CH', countryName: 'Switzerland', currencyCode: 'CHF', currencyName: 'Swiss Franc' },
  { countryCode: 'SY', countryName: 'Syria', currencyCode: 'SYP', currencyName: 'Syrian Pound' },
  {
    countryCode: 'TW',
    countryName: 'Taiwan, Province of China',
    currencyCode: 'TWD',
    currencyName: 'New Taiwan Dollar',
  },
  { countryCode: 'TJ', countryName: 'Tajikistan', currencyCode: 'TJS', currencyName: 'Somoni' },
  {
    countryCode: 'TZ',
    countryName: 'Tanzania, United Republic of',
    currencyCode: 'TZS',
    currencyName: 'Tanzanian Shilling',
  },
  { countryCode: 'TH', countryName: 'Thailand', currencyCode: 'THB', currencyName: 'Baht' },
  { countryCode: 'TL', countryName: 'Timor-Leste', currencyCode: 'USD', currencyName: 'US Dollar' },
  { countryCode: 'TG', countryName: 'Togo', currencyCode: 'XOF', currencyName: 'CFA Franc BCEAO' },
  { countryCode: 'TK', countryName: 'Tokelau', currencyCode: 'NZD', currencyName: 'New Zealand Dollar' },
  { countryCode: 'TO', countryName: 'Tonga', currencyCode: 'TOP', currencyName: 'Pa\u0092anga' },
  {
    countryCode: 'TT',
    countryName: 'Trinidad and Tobago',
    currencyCode: 'TTD',
    currencyName: 'Trinidad and Tobago Dollar',
  },
  { countryCode: 'TN', countryName: 'Tunisia', currencyCode: 'TND', currencyName: 'Tunisian Dinar' },
  { countryCode: 'TR', countryName: 'Turkey', currencyCode: 'TRY', currencyName: 'Turkish Lira' },
  { countryCode: 'TM', countryName: 'Turkmenistan', currencyCode: 'TMT', currencyName: 'Turkmenistan New Manat' },
  { countryCode: 'TC', countryName: 'Turks and Caicos Islands', currencyCode: 'USD', currencyName: 'US Dollar' },
  { countryCode: 'TV', countryName: 'Tuvalu', currencyCode: 'AUD', currencyName: 'Australian Dollar' },
  { countryCode: 'UG', countryName: 'Uganda', currencyCode: 'UGX', currencyName: 'Uganda Shilling' },
  { countryCode: 'UA', countryName: 'Ukraine', currencyCode: 'UAH', currencyName: 'Hryvnia' },
  { countryCode: 'AE', countryName: 'United Arab Emirates', currencyCode: 'AED', currencyName: 'UAE Dirham' },
  { countryCode: 'GB', countryName: 'United Kingdom', currencyCode: 'GBP', currencyName: 'Pound Sterling' },
  {
    countryCode: 'UM',
    countryName: 'United States Minor Outlying Islands',
    currencyCode: 'USD',
    currencyName: 'US Dollar',
  },
  { countryCode: 'US', countryName: 'United States', currencyCode: 'USD', currencyName: 'US Dollar' },
  { countryCode: 'UY', countryName: 'Uruguay', currencyCode: 'UYU', currencyName: 'Peso Uruguayo' },
  { countryCode: 'UZ', countryName: 'Uzbekistan', currencyCode: 'UZS', currencyName: 'Uzbekistan Sum' },
  { countryCode: 'VU', countryName: 'Vanuatu', currencyCode: 'VUV', currencyName: 'Vatu' },
  { countryCode: 'VE', countryName: 'Venezuela', currencyCode: 'VES', currencyName: 'Bol\u00edvar Soberano' },
  { countryCode: 'VN', countryName: 'Viet Nam', currencyCode: 'VND', currencyName: 'Dong' },
  { countryCode: 'VG', countryName: 'Virgin Islands, British', currencyCode: 'USD', currencyName: 'US Dollar' },
  { countryCode: 'VI', countryName: 'Virgin Islands, U.S.', currencyCode: 'USD', currencyName: 'US Dollar' },
  { countryCode: 'WF', countryName: 'Wallis and Futuna', currencyCode: 'XPF', currencyName: 'CFP Franc' },
  { countryCode: 'EH', countryName: 'Western Sahara', currencyCode: 'MAD', currencyName: 'Moroccan Dirham' },
  { countryCode: 'YE', countryName: 'Yemen', currencyCode: 'YER', currencyName: 'Yemeni Rial' },
  { countryCode: 'ZM', countryName: 'Zambia', currencyCode: 'ZMW', currencyName: 'Zambian Kwacha' },
  { countryCode: 'ZW', countryName: 'Zimbabwe', currencyCode: 'ZWL', currencyName: 'Zimbabwe Dollar' },
].sort((a, b) => (a.countryName > b.countryName ? 1 : -1));

export const PHONE_CODES = [
  {
    name: 'Afghanistan',
    dial_code: '+93',
    code: 'AF',
  },
  {
    name: 'Aland Islands',
    dial_code: '+358',
    code: 'AX',
  },
  {
    name: 'Albania',
    dial_code: '+355',
    code: 'AL',
  },
  {
    name: 'Algeria',
    dial_code: '+213',
    code: 'DZ',
  },
  {
    name: 'AmericanSamoa',
    dial_code: '+1684',
    code: 'AS',
  },
  {
    name: 'Andorra',
    dial_code: '+376',
    code: 'AD',
  },
  {
    name: 'Angola',
    dial_code: '+244',
    code: 'AO',
  },
  {
    name: 'Anguilla',
    dial_code: '+1264',
    code: 'AI',
  },
  {
    name: 'Antarctica',
    dial_code: '+672',
    code: 'AQ',
  },
  {
    name: 'Antigua and Barbuda',
    dial_code: '+1268',
    code: 'AG',
  },
  {
    name: 'Argentina',
    dial_code: '+54',
    code: 'AR',
  },
  {
    name: 'Armenia',
    dial_code: '+374',
    code: 'AM',
  },
  {
    name: 'Aruba',
    dial_code: '+297',
    code: 'AW',
  },
  {
    name: 'Australia',
    dial_code: '+61',
    code: 'AU',
  },
  {
    name: 'Austria',
    dial_code: '+43',
    code: 'AT',
  },
  {
    name: 'Azerbaijan',
    dial_code: '+994',
    code: 'AZ',
  },
  {
    name: 'Bahamas',
    dial_code: '+1242',
    code: 'BS',
  },
  {
    name: 'Bahrain',
    dial_code: '+973',
    code: 'BH',
  },
  {
    name: 'Bangladesh',
    dial_code: '+880',
    code: 'BD',
  },
  {
    name: 'Barbados',
    dial_code: '+1246',
    code: 'BB',
  },
  {
    name: 'Belarus',
    dial_code: '+375',
    code: 'BY',
  },
  {
    name: 'Belgium',
    dial_code: '+32',
    code: 'BE',
  },
  {
    name: 'Belize',
    dial_code: '+501',
    code: 'BZ',
  },
  {
    name: 'Benin',
    dial_code: '+229',
    code: 'BJ',
  },
  {
    name: 'Bermuda',
    dial_code: '+1441',
    code: 'BM',
  },
  {
    name: 'Bhutan',
    dial_code: '+975',
    code: 'BT',
  },
  {
    name: 'Bolivia, Plurinational State of',
    dial_code: '+591',
    code: 'BO',
  },
  {
    name: 'Bosnia and Herzegovina',
    dial_code: '+387',
    code: 'BA',
  },
  {
    name: 'Botswana',
    dial_code: '+267',
    code: 'BW',
  },
  {
    name: 'Brazil',
    dial_code: '+55',
    code: 'BR',
  },
  {
    name: 'British Indian Ocean Territory',
    dial_code: '+246',
    code: 'IO',
  },
  {
    name: 'Brunei Darussalam',
    dial_code: '+673',
    code: 'BN',
  },
  {
    name: 'Bulgaria',
    dial_code: '+359',
    code: 'BG',
  },
  {
    name: 'Burkina Faso',
    dial_code: '+226',
    code: 'BF',
  },
  {
    name: 'Burundi',
    dial_code: '+257',
    code: 'BI',
  },
  {
    name: 'Cambodia',
    dial_code: '+855',
    code: 'KH',
  },
  {
    name: 'Cameroon',
    dial_code: '+237',
    code: 'CM',
  },
  {
    name: 'Canada',
    dial_code: '+1',
    code: 'CA',
  },
  {
    name: 'Cape Verde',
    dial_code: '+238',
    code: 'CV',
  },
  {
    name: 'Cayman Islands',
    dial_code: '+ 345',
    code: 'KY',
  },
  {
    name: 'Central African Republic',
    dial_code: '+236',
    code: 'CF',
  },
  {
    name: 'Chad',
    dial_code: '+235',
    code: 'TD',
  },
  {
    name: 'Chile',
    dial_code: '+56',
    code: 'CL',
  },
  {
    name: 'China',
    dial_code: '+86',
    code: 'CN',
  },
  {
    name: 'Christmas Island',
    dial_code: '+61',
    code: 'CX',
  },
  {
    name: 'Cocos (Keeling) Islands',
    dial_code: '+61',
    code: 'CC',
  },
  {
    name: 'Colombia',
    dial_code: '+57',
    code: 'CO',
  },
  {
    name: 'Comoros',
    dial_code: '+269',
    code: 'KM',
  },
  {
    name: 'Congo',
    dial_code: '+242',
    code: 'CG',
  },
  {
    name: 'Congo, The Democratic Republic of the Congo',
    dial_code: '+243',
    code: 'CD',
  },
  {
    name: 'Cook Islands',
    dial_code: '+682',
    code: 'CK',
  },
  {
    name: 'Costa Rica',
    dial_code: '+506',
    code: 'CR',
  },
  {
    name: "Cote d'Ivoire",
    dial_code: '+225',
    code: 'CI',
  },
  {
    name: 'Croatia',
    dial_code: '+385',
    code: 'HR',
  },
  {
    name: 'Cuba',
    dial_code: '+53',
    code: 'CU',
  },
  {
    name: 'Cyprus',
    dial_code: '+357',
    code: 'CY',
  },
  {
    name: 'Czech Republic',
    dial_code: '+420',
    code: 'CZ',
  },
  {
    name: 'Denmark',
    dial_code: '+45',
    code: 'DK',
  },
  {
    name: 'Djibouti',
    dial_code: '+253',
    code: 'DJ',
  },
  {
    name: 'Dominica',
    dial_code: '+1767',
    code: 'DM',
  },
  {
    name: 'Dominican Republic',
    dial_code: '+1849',
    code: 'DO',
  },
  {
    name: 'Ecuador',
    dial_code: '+593',
    code: 'EC',
  },
  {
    name: 'Egypt',
    dial_code: '+20',
    code: 'EG',
  },
  {
    name: 'El Salvador',
    dial_code: '+503',
    code: 'SV',
  },
  {
    name: 'Equatorial Guinea',
    dial_code: '+240',
    code: 'GQ',
  },
  {
    name: 'Eritrea',
    dial_code: '+291',
    code: 'ER',
  },
  {
    name: 'Estonia',
    dial_code: '+372',
    code: 'EE',
  },
  {
    name: 'Ethiopia',
    dial_code: '+251',
    code: 'ET',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    dial_code: '+500',
    code: 'FK',
  },
  {
    name: 'Faroe Islands',
    dial_code: '+298',
    code: 'FO',
  },
  {
    name: 'Fiji',
    dial_code: '+679',
    code: 'FJ',
  },
  {
    name: 'Finland',
    dial_code: '+358',
    code: 'FI',
  },
  {
    name: 'France',
    dial_code: '+33',
    code: 'FR',
  },
  {
    name: 'French Guiana',
    dial_code: '+594',
    code: 'GF',
  },
  {
    name: 'French Polynesia',
    dial_code: '+689',
    code: 'PF',
  },
  {
    name: 'Gabon',
    dial_code: '+241',
    code: 'GA',
  },
  {
    name: 'Gambia',
    dial_code: '+220',
    code: 'GM',
  },
  {
    name: 'Georgia',
    dial_code: '+995',
    code: 'GE',
  },
  {
    name: 'Germany',
    dial_code: '+49',
    code: 'DE',
  },
  {
    name: 'Ghana',
    dial_code: '+233',
    code: 'GH',
  },
  {
    name: 'Gibraltar',
    dial_code: '+350',
    code: 'GI',
  },
  {
    name: 'Greece',
    dial_code: '+30',
    code: 'GR',
  },
  {
    name: 'Greenland',
    dial_code: '+299',
    code: 'GL',
  },
  {
    name: 'Grenada',
    dial_code: '+1473',
    code: 'GD',
  },
  {
    name: 'Guadeloupe',
    dial_code: '+590',
    code: 'GP',
  },
  {
    name: 'Guam',
    dial_code: '+1671',
    code: 'GU',
  },
  {
    name: 'Guatemala',
    dial_code: '+502',
    code: 'GT',
  },
  {
    name: 'Guinea',
    dial_code: '+224',
    code: 'GN',
  },
  {
    name: 'Guinea-Bissau',
    dial_code: '+245',
    code: 'GW',
  },
  {
    name: 'Guyana',
    dial_code: '+595',
    code: 'GY',
  },
  {
    name: 'Haiti',
    dial_code: '+509',
    code: 'HT',
  },
  {
    name: 'Holy See (Vatican City State)',
    dial_code: '+379',
    code: 'VA',
  },
  {
    name: 'Honduras',
    dial_code: '+504',
    code: 'HN',
  },
  {
    name: 'Hong Kong',
    dial_code: '+852',
    code: 'HK',
  },
  {
    name: 'Hungary',
    dial_code: '+36',
    code: 'HU',
  },
  {
    name: 'Iceland',
    dial_code: '+354',
    code: 'IS',
  },
  {
    name: 'India',
    dial_code: '+91',
    code: 'IN',
  },
  {
    name: 'Indonesia',
    dial_code: '+62',
    code: 'ID',
  },
  {
    name: 'Iran, Islamic Republic of Persian Gulf',
    dial_code: '+98',
    code: 'IR',
  },
  {
    name: 'Iraq',
    dial_code: '+964',
    code: 'IQ',
  },
  {
    name: 'Ireland',
    dial_code: '+353',
    code: 'IE',
  },
  {
    name: 'Israel',
    dial_code: '+972',
    code: 'IL',
  },
  {
    name: 'Italy',
    dial_code: '+39',
    code: 'IT',
  },
  {
    name: 'Jamaica',
    dial_code: '+1876',
    code: 'JM',
  },
  {
    name: 'Japan',
    dial_code: '+81',
    code: 'JP',
  },
  {
    name: 'Jordan',
    dial_code: '+962',
    code: 'JO',
  },
  {
    name: 'Kazakhstan',
    dial_code: '+77',
    code: 'KZ',
  },
  {
    name: 'Kenya',
    dial_code: '+254',
    code: 'KE',
  },
  {
    name: 'Kiribati',
    dial_code: '+686',
    code: 'KI',
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    dial_code: '+850',
    code: 'KP',
  },
  {
    name: 'Korea, Republic of South Korea',
    dial_code: '+82',
    code: 'KR',
  },
  {
    name: 'Kuwait',
    dial_code: '+965',
    code: 'KW',
  },
  {
    name: 'Kyrgyzstan',
    dial_code: '+996',
    code: 'KG',
  },
  {
    name: 'Laos',
    dial_code: '+856',
    code: 'LA',
  },
  {
    name: 'Latvia',
    dial_code: '+371',
    code: 'LV',
  },
  {
    name: 'Lebanon',
    dial_code: '+961',
    code: 'LB',
  },
  {
    name: 'Lesotho',
    dial_code: '+266',
    code: 'LS',
  },
  {
    name: 'Liberia',
    dial_code: '+231',
    code: 'LR',
  },
  {
    name: 'Libyan Arab Jamahiriya',
    dial_code: '+218',
    code: 'LY',
  },
  {
    name: 'Liechtenstein',
    dial_code: '+423',
    code: 'LI',
  },
  {
    name: 'Lithuania',
    dial_code: '+370',
    code: 'LT',
  },
  {
    name: 'Luxembourg',
    dial_code: '+352',
    code: 'LU',
  },
  {
    name: 'Macao',
    dial_code: '+853',
    code: 'MO',
  },
  {
    name: 'Macedonia',
    dial_code: '+389',
    code: 'MK',
  },
  {
    name: 'Madagascar',
    dial_code: '+261',
    code: 'MG',
  },
  {
    name: 'Malawi',
    dial_code: '+265',
    code: 'MW',
  },
  {
    name: 'Malaysia',
    dial_code: '+60',
    code: 'MY',
  },
  {
    name: 'Maldives',
    dial_code: '+960',
    code: 'MV',
  },
  {
    name: 'Mali',
    dial_code: '+223',
    code: 'ML',
  },
  {
    name: 'Malta',
    dial_code: '+356',
    code: 'MT',
  },
  {
    name: 'Marshall Islands',
    dial_code: '+692',
    code: 'MH',
  },
  {
    name: 'Martinique',
    dial_code: '+596',
    code: 'MQ',
  },
  {
    name: 'Mauritania',
    dial_code: '+222',
    code: 'MR',
  },
  {
    name: 'Mauritius',
    dial_code: '+230',
    code: 'MU',
  },
  {
    name: 'Mayotte',
    dial_code: '+262',
    code: 'YT',
  },
  {
    name: 'Mexico',
    dial_code: '+52',
    code: 'MX',
  },
  {
    name: 'Micronesia, Federated States of Micronesia',
    dial_code: '+691',
    code: 'FM',
  },
  {
    name: 'Moldova',
    dial_code: '+373',
    code: 'MD',
  },
  {
    name: 'Monaco',
    dial_code: '+377',
    code: 'MC',
  },
  {
    name: 'Mongolia',
    dial_code: '+976',
    code: 'MN',
  },
  {
    name: 'Montenegro',
    dial_code: '+382',
    code: 'ME',
  },
  {
    name: 'Montserrat',
    dial_code: '+1664',
    code: 'MS',
  },
  {
    name: 'Morocco',
    dial_code: '+212',
    code: 'MA',
  },
  {
    name: 'Mozambique',
    dial_code: '+258',
    code: 'MZ',
  },
  {
    name: 'Myanmar',
    dial_code: '+95',
    code: 'MM',
  },
  {
    name: 'Namibia',
    dial_code: '+264',
    code: 'NA',
  },
  {
    name: 'Nauru',
    dial_code: '+674',
    code: 'NR',
  },
  {
    name: 'Nepal',
    dial_code: '+977',
    code: 'NP',
  },
  {
    name: 'Netherlands',
    dial_code: '+31',
    code: 'NL',
  },
  {
    name: 'Netherlands Antilles',
    dial_code: '+599',
    code: 'AN',
  },
  {
    name: 'New Caledonia',
    dial_code: '+687',
    code: 'NC',
  },
  {
    name: 'New Zealand',
    dial_code: '+64',
    code: 'NZ',
  },
  {
    name: 'Nicaragua',
    dial_code: '+505',
    code: 'NI',
  },
  {
    name: 'Niger',
    dial_code: '+227',
    code: 'NE',
  },
  {
    name: 'Nigeria',
    dial_code: '+234',
    code: 'NG',
  },
  {
    name: 'Niue',
    dial_code: '+683',
    code: 'NU',
  },
  {
    name: 'Norfolk Island',
    dial_code: '+672',
    code: 'NF',
  },
  {
    name: 'Northern Mariana Islands',
    dial_code: '+1670',
    code: 'MP',
  },
  {
    name: 'Norway',
    dial_code: '+47',
    code: 'NO',
  },
  {
    name: 'Oman',
    dial_code: '+968',
    code: 'OM',
  },
  {
    name: 'Pakistan',
    dial_code: '+92',
    code: 'PK',
  },
  {
    name: 'Palau',
    dial_code: '+680',
    code: 'PW',
  },
  {
    name: 'Palestinian Territory, Occupied',
    dial_code: '+970',
    code: 'PS',
  },
  {
    name: 'Panama',
    dial_code: '+507',
    code: 'PA',
  },
  {
    name: 'Papua New Guinea',
    dial_code: '+675',
    code: 'PG',
  },
  {
    name: 'Paraguay',
    dial_code: '+595',
    code: 'PY',
  },
  {
    name: 'Peru',
    dial_code: '+51',
    code: 'PE',
  },
  {
    name: 'Philippines',
    dial_code: '+63',
    code: 'PH',
  },
  {
    name: 'Pitcairn',
    dial_code: '+872',
    code: 'PN',
  },
  {
    name: 'Poland',
    dial_code: '+48',
    code: 'PL',
  },
  {
    name: 'Portugal',
    dial_code: '+351',
    code: 'PT',
  },
  {
    name: 'Puerto Rico',
    dial_code: '+1939',
    code: 'PR',
  },
  {
    name: 'Qatar',
    dial_code: '+974',
    code: 'QA',
  },
  {
    name: 'Romania',
    dial_code: '+40',
    code: 'RO',
  },
  {
    name: 'Russia',
    dial_code: '+7',
    code: 'RU',
  },
  {
    name: 'Rwanda',
    dial_code: '+250',
    code: 'RW',
  },
  {
    name: 'Reunion',
    dial_code: '+262',
    code: 'RE',
  },
  {
    name: 'Saint Barthelemy',
    dial_code: '+590',
    code: 'BL',
  },
  {
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    dial_code: '+290',
    code: 'SH',
  },
  {
    name: 'Saint Kitts and Nevis',
    dial_code: '+1869',
    code: 'KN',
  },
  {
    name: 'Saint Lucia',
    dial_code: '+1758',
    code: 'LC',
  },
  {
    name: 'Saint Martin',
    dial_code: '+590',
    code: 'MF',
  },
  {
    name: 'Saint Pierre and Miquelon',
    dial_code: '+508',
    code: 'PM',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    dial_code: '+1784',
    code: 'VC',
  },
  {
    name: 'Samoa',
    dial_code: '+685',
    code: 'WS',
  },
  {
    name: 'San Marino',
    dial_code: '+378',
    code: 'SM',
  },
  {
    name: 'Sao Tome and Principe',
    dial_code: '+239',
    code: 'ST',
  },
  {
    name: 'Saudi Arabia',
    dial_code: '+966',
    code: 'SA',
  },
  {
    name: 'Senegal',
    dial_code: '+221',
    code: 'SN',
  },
  {
    name: 'Serbia',
    dial_code: '+381',
    code: 'RS',
  },
  {
    name: 'Seychelles',
    dial_code: '+248',
    code: 'SC',
  },
  {
    name: 'Sierra Leone',
    dial_code: '+232',
    code: 'SL',
  },
  {
    name: 'Singapore',
    dial_code: '+65',
    code: 'SG',
  },
  {
    name: 'Slovakia',
    dial_code: '+421',
    code: 'SK',
  },
  {
    name: 'Slovenia',
    dial_code: '+386',
    code: 'SI',
  },
  {
    name: 'Solomon Islands',
    dial_code: '+677',
    code: 'SB',
  },
  {
    name: 'Somalia',
    dial_code: '+252',
    code: 'SO',
  },
  {
    name: 'South Africa',
    dial_code: '+27',
    code: 'ZA',
  },
  {
    name: 'South Sudan',
    dial_code: '+211',
    code: 'SS',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    dial_code: '+500',
    code: 'GS',
  },
  {
    name: 'Spain',
    dial_code: '+34',
    code: 'ES',
  },
  {
    name: 'Sri Lanka',
    dial_code: '+94',
    code: 'LK',
  },
  {
    name: 'Sudan',
    dial_code: '+249',
    code: 'SD',
  },
  {
    name: 'Suriname',
    dial_code: '+597',
    code: 'SR',
  },
  {
    name: 'Svalbard and Jan Mayen',
    dial_code: '+47',
    code: 'SJ',
  },
  {
    name: 'Swaziland',
    dial_code: '+268',
    code: 'SZ',
  },
  {
    name: 'Sweden',
    dial_code: '+46',
    code: 'SE',
  },
  {
    name: 'Switzerland',
    dial_code: '+41',
    code: 'CH',
  },
  {
    name: 'Syrian Arab Republic',
    dial_code: '+963',
    code: 'SY',
  },
  {
    name: 'Taiwan',
    dial_code: '+886',
    code: 'TW',
  },
  {
    name: 'Tajikistan',
    dial_code: '+992',
    code: 'TJ',
  },
  {
    name: 'Tanzania, United Republic of Tanzania',
    dial_code: '+255',
    code: 'TZ',
  },
  {
    name: 'Thailand',
    dial_code: '+66',
    code: 'TH',
  },
  {
    name: 'Timor-Leste',
    dial_code: '+670',
    code: 'TL',
  },
  {
    name: 'Togo',
    dial_code: '+228',
    code: 'TG',
  },
  {
    name: 'Tokelau',
    dial_code: '+690',
    code: 'TK',
  },
  {
    name: 'Tonga',
    dial_code: '+676',
    code: 'TO',
  },
  {
    name: 'Trinidad and Tobago',
    dial_code: '+1868',
    code: 'TT',
  },
  {
    name: 'Tunisia',
    dial_code: '+216',
    code: 'TN',
  },
  {
    name: 'Turkey',
    dial_code: '+90',
    code: 'TR',
  },
  {
    name: 'Turkmenistan',
    dial_code: '+993',
    code: 'TM',
  },
  {
    name: 'Turks and Caicos Islands',
    dial_code: '+1649',
    code: 'TC',
  },
  {
    name: 'Tuvalu',
    dial_code: '+688',
    code: 'TV',
  },
  {
    name: 'Uganda',
    dial_code: '+256',
    code: 'UG',
  },
  {
    name: 'Ukraine',
    dial_code: '+380',
    code: 'UA',
  },
  {
    name: 'United Arab Emirates',
    dial_code: '+971',
    code: 'AE',
  },
  {
    name: 'United Kingdom',
    dial_code: '+44',
    code: 'GB',
  },
  {
    name: 'United States',
    dial_code: '+1',
    code: 'US',
  },
  {
    name: 'Uruguay',
    dial_code: '+598',
    code: 'UY',
  },
  {
    name: 'Uzbekistan',
    dial_code: '+998',
    code: 'UZ',
  },
  {
    name: 'Vanuatu',
    dial_code: '+678',
    code: 'VU',
  },
  {
    name: 'Venezuela, Bolivarian Republic of Venezuela',
    dial_code: '+58',
    code: 'VE',
  },
  {
    name: 'Vietnam',
    dial_code: '+84',
    code: 'VN',
  },
  {
    name: 'Virgin Islands, British',
    dial_code: '+1284',
    code: 'VG',
  },
  {
    name: 'Virgin Islands, U.S.',
    dial_code: '+1340',
    code: 'VI',
  },
  {
    name: 'Wallis and Futuna',
    dial_code: '+681',
    code: 'WF',
  },
  {
    name: 'Yemen',
    dial_code: '+967',
    code: 'YE',
  },
  {
    name: 'Zambia',
    dial_code: '+260',
    code: 'ZM',
  },
  {
    name: 'Zimbabwe',
    dial_code: '+263',
    code: 'ZW',
  },
];

export const PERSON_RELATIONSHIPS = ['Spouse', 'Parents'];

export const NA_SYMBOL = '-';

export const ADDRESS_REGEX = /^[ A-Za-z0-9_'*(),./@#&+-]*$/;

export const POSTCODE_REGEX = /^[ A-Za-z0-9-]*$/;

export const PHONE_REGEX = /^(\+)?(\(?\d+\)?)(([\s-]+)?(\d+)){0,30}$/;

export namespace RetirementConstants {
  export const RET_SUBMISSION_MIN_WINDOW_IN_DAYS = 7;
  export const DB_RET_CASE_PROC_WINDOW_IN_DAYS = 30;
  export const DC_RET_CASE_PROC_WINDOW_IN_DAYS = 21;
  export const DB_RET_PROC_PERIOD_IN_DAYS = RET_SUBMISSION_MIN_WINDOW_IN_DAYS + DB_RET_CASE_PROC_WINDOW_IN_DAYS;
  export const EARLIEST_RET_AGE_IN_YEARS = 55;
  export const LATEST_RET_AGE_IN_YEARS = 75;
}
